### ISSUE TITLE
inspect.iscoroutinefunction on old Python 3.6 version

### ISSUE THREAD

**Issue by keans** [MushroomMaula/fastapi_login#103]
Hi,

at work I need use an old Python 3.6 version (sadly no way of upgrading :-( ). However, there seems to be a problem for the `inspect.iscoroutinefunction` in the `_load_user` function that is not correctly returning true so that the async function will not be called with await, resulting in unwanted behavior.

Maybe I found a possible reason for that here: https://devpress.csdn.net/python/63045bc8c67703293080bc80.html

So it seems that for old Python version < 3.8 the result will be wrong when called on the partial. Is there any chance to officially fix this to make it work for old Python versions?

**Comment by MushroomMaula** [comment]
If I understand correctly this issue occurs when the `user_loader` is a `functools.partial` object and not a normal function correct?

**Comment by keans** [comment]
Simple example:

```
import inspect
import platform

from fastapi_login.utils import ordered_partial

def no_coroutine():
	print("I am not a coroutine")

async def coroutine():
	print("I am a coroutine")

print("Python", platform.python_version())

func = ordered_partial(no_coroutine)
print("iscoroutinefunc 'no_coroutine':", inspect.iscoroutinefunction(func))

func = ordered_partial(coroutine)
print("iscoroutinefunc of 'coroutine' .func:", inspect.iscoroutinefunction(func.func))
print("iscoroutinefunc of 'coroutine':", inspect.iscoroutinefunction(func))

```

Output of script called with Python 3.6:
```
Python 3.6.15
iscoroutinefunc 'no_coroutine': False
iscoroutinefunc of 'coroutine' .func: True
iscoroutinefunc of 'coroutine': False
```

Output of script called with Python 3.10:
```
Python 3.10.10
iscoroutinefunc 'no_coroutine': False
iscoroutinefunc of 'coroutine' .func: True
iscoroutinefunc of 'coroutine': True
```

This means, if the callback function `self._user_callback` is a coroutine and `ordered_partial` is applied, the inspect `iscoroutinefunction` will return False in Python 3.6 while for newer Pythons it returns True. 

I think an easy workaround would be to use instead of `inspect.iscoroutinefunction` the following function:

```
def iscoroutinefunction_or_partial(object):
    while isinstance(object, functools.partial):
        object = object.func
    return inspect.iscoroutinefunction(object)
```
Then, simply replace `if inspect.iscoroutinefunction(self._user_callback)` by `if iscoroutinefunction_or_partial(self._user_callback)`.

**Comment by keans** [comment]
Any chance to get this fix into the upstream version? Fixing this manually is quite tedious.

**Comment by MushroomMaula** [comment]
Hey, sorry for not responding for so long. I don't have much time working on this, and python 3.6 is no longer supported, neither by fastapi nor by this package, so there will probably be no fix any time soon. 
If you want, you can submit a PR and I will most likely merge it.

**Comment by kigawas** [comment]
Python 3.8 is the minimum version supported so this will not be fixed
