### ISSUE TITLE
Value of the user parameter in path operations?

### ISSUE THREAD

**Issue by nocturn9x** [MushroomMaula/fastapi_login#12]
Hi, I stumbled upon this project while developing a backend with FastAPI and I'm amazed by the ease of use and completeness of this work. I was wondering what's the actual value of the user parameter defines as `user = Depends(manager)`? Because I have some functions that, for instance, allow users to delete their account and I need to check if user foobar actually wants to delete his own account or someone else's account (that would be weird wouldn't it). Thanks in advance and Kind regards

**Comment by MushroomMaula** [comment]
Upon calling `Depends(manager)` the `__call__ `method of the manager is executed, this decrypts the JWT and executes the callback, you have set using the decorator, with the value of the `sub` key of the JWT's payload. Therefore the returned value is the value returned by your callback.
Lets say this is your callback:
```py
@manager.user_loader
def my_callback(user_id):
    return "My user"
```
Returned value would always be `"My user"` (assuming the JWT is actually valid) obiviously this is a highly unrealistic example as you normally would take the user_id and query your database.
So if you want to check if the user wants to delete his own accout or someone elses you could just check if the users id (returned by your callback) matches the one in the request.

I hope this helps

**Comment by nocturn9x** [comment]
Amazing, thanks, that's exactly the info I needed
