### ISSUE TITLE
Use a different name for the token in the header

### ISSUE THREAD

**Issue by tim-habitat** [MushroomMaula/fastapi_login#130]
Would it be possible to overwrite the name of the token that is expected in the `authorization` header?
i.e look for the token in `authorization` with the value `Token xxx-secret`

in  particular, i think it might be derived from `oauth2` instead of the bearer impl. from fastapi.
https://github.com/tiangolo/fastapi/blob/eef1b7d51530be64ddd48e02b5ca46f28a0ebfc1/fastapi/security/oauth2.py#L391

happy to submit a pr if that sounds good.

**Comment by tim-habitat** [comment]
actually think we could just not call the `super.__call__` [here](https://github.com/MushroomMaula/fastapi_login/blob/44cdbb4c874b1d0c68d307acca86c02a76215f68/fastapi_login/fastapi_login.py#L343)
and just reimplement the logic

**Comment by kigawas** [comment]
Yes it's just inheritance. If you want to customize you can also inherit the LoginManager
