### ISSUE TITLE
No way to register a user?

### ISSUE THREAD

**Issue by openSourceBugs** [MushroomMaula/fastapi_login#132]
It doesn't seem like the docs mention this at all.  I'm going to assume this is broken until otherwise informed.  You can't login without registering a user first.  As it is, the documentation assumes plain text in database passwords, a big no no.

**Comment by kigawas** [comment]
This is an authentication library, not a database usage tutorial for managing users. It's just for creating a token, whether the token should be created or not depends on implementation
