### ISSUE TITLE
Login expires after 15min (or any other value you set), how to refresh?

### ISSUE THREAD

**Issue by nrathaus** [MushroomMaula/fastapi_login#136]
I am looking at a solution to "refresh" the cookie/jwt value so that 15min becomes 'inactivity' timer, not a default time when the JWT expires

For example, while the user interacts with the system - the cookie remains valid (obviously he needs to reach out to the app API interfaces), if he has not reached out to the API interface the cookie/JWT will become invalid after 15min

I noted that there are some other similar issues raised such as:
https://github.com/MushroomMaula/fastapi_login/issues/45

But it doesn't clarify how to do what I asked, I also looked at "full-example" but it doesn't explain how to 'refresh' or revalidate an existing JWT

Thank you for the help

**Comment by kigawas** [comment]
JWT's exp is fixed in the payload, you cannot change it without generating a new token

**Comment by nrathaus** [comment]
Thank you for answering

I read more about it and I see your point

How would you refresh the token? I noted in the other issue that you should make an api end point to refresh it

Is there a way to know when the token will soon expire? I don't see it from the fastapi_login?

**Comment by kigawas** [comment]
You need to implement your own logic. For example, check the exp at frontend and call a refresh token API.
fastapi_login is for generating JWT, not for managing sessions

**Comment by nrathaus** [comment]
For the sake of helping others, here is the solution I created:
```
let refresh_token = localStorage.getItem("refresh_token");

function check_token() {
  let elapsed = 0;
  if (refresh_token) {
    elapsed = (Date.now() - refresh_token) / 1000;
    console.log(`Token going to expire in: ${15 * 60 - elapsed} seconds`);
  }

  if (!refresh_token || 15 * 60 - elapsed < 1 * 60) {
    // Token is going to invalidate in less than 1 minute
    $.ajax({
      url: "/refresh/token",
    }).then(function (response) {
      refresh_token = Date.now(); // Store when the token was last refreshed
      localStorage.setItem("refresh_token", refresh_token);
    });
  }

  setTimeout(function () {
    check_token();
  }, 5000);
}

// Check ever 5 seconds for the token validity
setTimeout(function () {
  check_token();
}, 5000);
```

```

@app.get("/refresh/token")
def refresh_token(response: Response, user=Depends(manager)) -> dict:
    """Refresh Token"""

    access_token = manager.create_access_token(data=dict(sub=user["email"]))
    manager.set_cookie(response, access_token)
    return {"access_token": access_token, "token_type": "bearer"}
```
