### ISSUE TITLE
Cookie expiration

### ISSUE THREAD

**Issue by DevilWarrior** [MushroomMaula/fastapi_login#14]
Hi, I currently have things setup where I use cookies with fastapi_login.

```
manager = LoginManager(SECRET, tokenUrl='/auth/token', use_cookie=True)
manager.cookie_name = 'oversight_token'
```

On the auth route I build a response object with a RedirectResponse and set the cookie there.

```
access_token = manager.create_access_token(
    data=dict(sub=email)
)

response = RedirectResponse(url='/bids')
response.set_cookie(
    key=manager.cookie_name,
    value=f"Bearer {access_token}",
    httponly=True,
    max_age=2147483647,
    expires=2147483647,
)
return response
```

I have tried setting the **max_age** and **expires** values for the cookie to the maximum I could but after a while the site requires me to sign again. So my question is, how can I extend this time to the maximum? I'm behind a couple of firewalls and and internal VPN so security after login is not an issue for me. I'm have a couple of other minor issues but I'll create separate issues for those.

**Comment by MushroomMaula** [comment]
Have you tried changing the expiry on the access token? The default is 15 minutes therefore by default every token becomes default afterwards. You can change the expiry time by using the `expires_delta` parameter in the `create_access_token` method.

```py
import datetime

year_in_hours = 365*25

access_token = manager.create_access_token(
    data=dict(sub=email),
    expires_delta=datetime.timedelta(year_in_hours)
)
```
This token would now be valid for a year. Please note that this is propably not a good idea as if the token is stolen the attacker now has access to the application for a year. A good idea is to look into access tokens and refresh tokens which issuse new access tokens after a certain time.

**Comment by DevilWarrior** [comment]
HI thanks for the prompt response, will try this right away. Yeah, I won't set it up for a whole year. I don't mind if the users have to login again after a day or two. But 15 min would drive them insane since they use the site throughout the day. I'm in a small studio without internet access, behind a VPN and multiple firewalls. The site will be available only within the studio. The only reason why i'm setting a login page here is to limit access to other users but security is not as important as user experience on this particular case. Thank you!!!
