### ISSUE TITLE
Upgrade anyio[trio] version to above 4

### ISSUE THREAD

**Issue by IterableTrucks** [MushroomMaula/fastapi_login#143]
anyio<4.0 will restrict the trio version under 0.22.0 which will cause conflict with loguru>=0.7.0 and emit the warning: 

> trio/_core/_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.

The Python version is 3.9.18

**Comment by kigawas** [comment]
Anyio is used by fastapi, we don't have to upgrade it, just following fastapi's anyio version

**Comment by IterableTrucks** [comment]
Fastapi requires Anyio indirectly by Starlette, and in the lastest version of Starlette the anyio version requirement is `anyio>=3.4.0,<5`. So there seems no reason  for remaining a tighter version constraint `anyio = {version = "^3.6.2", extras = ["trio"]}` which means `anyio>=3.6.2,<4` in fastapi-login's dependencies.

**Comment by kigawas** [comment]
released
