### ISSUE TITLE
Redirects after login

### ISSUE THREAD

**Issue by DevilWarrior** [MushroomMaula/fastapi_login#15]
Hi,  I currently have things setup where I use cookies with fastapi_login.

```
manager = LoginManager(SECRET, tokenUrl='/auth/token', use_cookie=True)
manager.cookie_name = 'oversight_token'
```

On the auth route I build a response object with a RedirectResponse and set the cookie there.

```
access_token = manager.create_access_token(
    data=dict(sub=email)
)

response = RedirectResponse(url='/bids')
response.set_cookie(
    key=manager.cookie_name,
    value=f"Bearer {access_token}",
    httponly=True,
    max_age=2147483647,
    expires=2147483647,
)
return response
```

This works only if the redirect has a POST method, does not work for GET routes. Is that the expected behavior? I'm new to fastapi, sorry for the noob question.

**Comment by MushroomMaula** [comment]
So you are saying you can only set the cookie if `'/bids'` has a POST method? That seems quite weird

**Comment by MushroomMaula** [comment]
After searching found this issue on the [FastAPI repo](https://github.com/tiangolo/fastapi/issues/863) which should solve your problem

**Comment by DevilWarrior** [comment]
Thank you!!!!
