### ISSUE TITLE
Exception thrown trying to decode jwt

### ISSUE THREAD

**Issue by ttymck** [MushroomMaula/fastapi_login#21]
```
File "./api/routes.py", line 38, in login
    token = login_manager.create_access_token(data=data, expires_delta=timedelta(days=30))
  File "/path/to/my/.venv/lib/python3.8/site-packages/fastapi_login/fastapi_login.py", line 165, in create_access_token
    return encoded_jwt.decode()
AttributeError: 'str' object has no attribute 'decode'
```

It looks like that [line of code](https://github.com/MushroomMaula/fastapi_login/blob/master/fastapi_login/fastapi_login.py#L165) is assuming the `encoded_jwt` is bytes, but it looks like that [method returns a string](https://pyjwt.readthedocs.io/en/stable/api.html#jwt.encode).

My Pipfile.lock resolved pyjwt to version `==2.0.0`, I suppose this is a breaking change from [1.7.1](https://github.com/MushroomMaula/fastapi_login/blob/master/Pipfile.lock#L120), and I should restrict my Pipfile accordingly?

**Comment by MushroomMaula** [comment]
Thanks for raising awareness of this issue I 'm going to update pyjwt to its latest version and fix the error

**Comment by MushroomMaula** [comment]
I just updated the package and now everything should be working fine with the latest version of pyjwt
