### ISSUE TITLE
I'm trying to create a login page using jinja2.

### ISSUE THREAD

**Issue by mturu1976** [MushroomMaula/fastapi_login#23]
I'm trying to create a login page using jinja2.

    File "./main.py", line 37, in login
      manager.set_cookie(resp,access_token)
  AttributeError: 'LoginManager' object has no attribute 'set_cookie'

What should I do?
  
    from fastapi import FastAPI,Depends
    from fastapi.responses import RedirectResponse,HTMLResponse
    from fastapi.security import OAuth2PasswordRequestForm
    from fastapi_login.exceptions import InvalidCredentialsException
    from fastapi.templating import Jinja2Templates
    from fastapi_login import LoginManager
    import os
  
    SECRET = "your-secret-key"
    fake_db = {'johndoe@e.mail': {'password': 'hunter2'}}
    manager = LoginManager(SECRET, tokenUrl='/auth/token')
    
    app = FastAPI()
    
    pth = os.path.dirname(__file__)
    templates = Jinja2Templates(directory=os.path.join(pth, "templates"))
    
    @manager.user_loader
    def load_user(email: str):  # could also be an asynchronous function
        user = fake_db.get(email)
        return user
  
    @app.post('/auth/token')
    def login(data: OAuth2PasswordRequestForm = Depends()):
        email = data.username
        password = data.password
  
      user = load_user(email)  # we are using the same function to retrieve the user
      if not user:
          raise InvalidCredentialsException  # you can also use your own HTTPException
      elif password != user['password']:
          raise InvalidCredentialsException
      
      access_token = manager.create_access_token(
          data=dict(sub=email)
      )
      
      resp = RedirectResponse(url="/protected")
      manager.set_cookie(resp,access_token)
      return resp
      # return {'access_token': access_token, 'token_type': 'bearer'}
  
    @app.get('/protected')
    def protected_route(user=Depends(manager)):
        with open(os.path.join(pth, "templates/protectedpage.html")) as f:
            return HTMLResponse(content=f.read())
    
    
    @app.get("/",response_class=HTMLResponse)
    def loginwithCreds():
        with open(os.path.join(pth, "templates/login.html")) as f:
            return HTMLResponse(content=f.read())

**Comment by MushroomMaula** [comment]
Your example is working fine for me.
What version of fastapi-login are you ussing? You can check with `pip list`.

**Comment by mturu1976** [comment]
Thanks for the comment.
fastapi-login            1.5.0
It was 1.5.0.

**Comment by MushroomMaula** [comment]
The `set_cookie` has only been added in version 1.5.1. so you need to upgrade in order to use the `set_cookie` method.

**Comment by mturu1976** [comment]
Thank you very much. I didn't realize that the version was old.
