### ISSUE TITLE
How to check if an user is logged in 

### ISSUE THREAD

**Issue by jccolazo** [MushroomMaula/fastapi_login#25]
Im currently using the manager with cookies. But I want to redirect to '/' when someone who is logged in tries to go to '/login' page.

**Comment by MushroomMaula** [comment]
Do you only want to redirect on `GET` Requests or also on the `POST` requests made to the `/login` route? 
If you want to redirect on the `POST` request, I'm afraid there is currently no simple way to make it work as an unauthenticated request, to a route using the `LoginManager` as a dependency by default results in an `HTTP_401` status code.
One option that could work is checking by hand if the user is logged in and catching a possible ``HTTPException`` if the user is not:

```python
from fastapi import HTTPException
from starlette.responses import RedirectResponse

@app.post('/login')
async def login(request: Request, data: OAuth2PasswordRequestForm = Depends()):
    # check if user is already logged in
    try:
        user = await manager(request)   # can raise HTTP_401 when user is not logged in
        # redirect logged in user to homepage
        return RedirectResponse('/')
    except HTTPException:
        # Your is not logged in, resume with normal log in
        pass
    
    # Your normal log in flow
    ...
```

I'm open for suggestions how this workflow could be made simpler.

However if its just the `GET` requests you want to redirect, there should be no problem adding your `LoginManager` instance as an dependency.

```python
from starlette.responses import RedirectResponse

@app.get('/login')
def login(user=Depends(manager)):
    """ Show login form """
    if user:
         return RedirectResponse('/')
    ...
```

**Comment by jccolazo** [comment]
@MushroomMaula Thank you very much! It is for both post and get, and it's working!
