### ISSUE TITLE
exception not showing up in html template

### ISSUE THREAD

**Issue by mclima** [MushroomMaula/fastapi_login#26]
Hello, I'm new to API and your library in general. 

I'm passing the InvalidCredentialsException as you suggested in your readme. However while the exception is working, the exception is throwing a blank page on my browser, (with the exception message) instead of the html with my login page. Is there way you can help?

**Comment by MushroomMaula** [comment]
Normally a REST API is used in combination with a frontend framework such React or Vue, which render on the client side. When you make a call to the API and get an error the framework handels this error and displays some information or whatever you want to show the user.
If you are using HTML templates however you are rendering on the server side and it doesn't really benefit you to return a HTTP error code such as 401 Unauthorized, that is the error code of the `InvalidCredentialsException`. In that case however I suggest you do not return the `InvalidCredentialsException`, but rather the login template with some error message kind of like this:

```py
@app.post('/auth/token')
def login(data: OAuth2PasswordRequestForm = Depends()):

    if not user:
        # show error message on the frontend
        return TemplateResponse('login.html',  {'error': 'Invalid credentials'})
    elif password != user['password']:
        return TemplateResponse('login.html',  {'error': 'Invalid credentials'})
```
```html
<!-- this would be the login template, with name "login.html" -->
<form>
    {% if error is defined %}
        {# 
            Notice that "error" is the key of the message we pass as 
            arguments to the template in the route 
        #}
        <p>{{ error }}</p>
    {% endif %}
    <label for="email">
        E-Mail
        <input id="email"></input>
    </label>
    <label for="password">
        Password
        <input id="password" type="password"></input>
    </label>
</form>
```

**Comment by mclima** [comment]
Thank, it worked.  greatly appreciated!
