### ISSUE TITLE
Using with sqlachemy.orm.session

### ISSUE THREAD

**Issue by sid3r** [MushroomMaula/fastapi_login#29]
Hey thank you for the package, I'm still trying it out the login works fine, this is maybe related heavily to the package but I have some errors raising due to the use of sqlalchemy session, any help is welcome.

 I'm trying to pass extra parameters to **def load_user(email: str)** like this

`@auth_manager.user_loader`
`def load_user(email: str, db: Session):`
`    user = actions.user.get_by_email(db=db, email=email)`
`    return user`

i'm passing an **sqlalchemy db session** to the **load_user** function which like as said before, works fine on **/auth/token**, **the token is generated**. the error raise when trying to access routes protected by the **manager**:

`fastapi_login/fastapi_login.py", line 140`
`load_user() missing 1 required positional argument: 'db'`

is there a way to make the second parameter optional ?

**Comment by MushroomMaula** [comment]
Hey, its not easily done because internally the arguments passed to ``user_loader`` are taken from the token.
I assume your sqlalchemy session stays the same so you could just create a function which already has the  session as an argument:

```python
DB = your_sqlalchemy_session
auth_manager.user_loader(lambda email: action.user.get_by_email(db=DB, email=email))
```

If this doesn't help the way I've done it before:

```py
# most of this part is taken from the sqlalchemy session docs
from contextlib import contextmanager

Session = sessionmaker(bind=engine)

@contextmanager
def temp_session():
    """Provide a transactional scope around a series of operations."""
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()

@auth_manager.user_loader
def load_user(email:str, db: Session = None):
    if db is None:
        with temp_session() as db:
            user = actions.user.get_by_email(db=db, email=email)
    else:
        user = actions.user.get_by_email(db=db, email=email)
    return user
```

**Comment by sid3r** [comment]
@MushroomMaula I already have a function that returns the DB session: 

```python
def get_db():
  try:
    db = SessionLocal()
    yield db
  finally:
    db.close()
```
I've wasted some time on this so I've started my simple jwt implementation but I'll give it a try and come back. thank you.

**Comment by MushroomMaula** [comment]
In this case you you can just replace the with context in the second example with a call to your get_db  function. I'll consider the ability to add other arguments to the user_loader in future releases.

**Comment by sid3r** [comment]
@MushroomMaula Same issue, the login works fine:

```python
auth_manager = LoginManager(settings.SECRET, tokenUrl='/auth/login')

# get db session
def get_db():
  try:
    db = SessionLocal()
    yield db
  finally:
    db.close()

@auth_manager.user_loader
def load_user(email: str, db: Session = None):
  if db is None:
    db = get_db()
    user = actions.user.get_by_email(db=db, email=email)
  else:
    user = actions.user.get_by_email(db=db, email=email)
  return user
```

```python
@app.post('/auth/login', tags=["users"])
def login(*, db: Session = Depends(get_db), data: OAuth2PasswordRequestForm = Depends()):
    email = data.username
    password = data.password
    user = load_user(email, db)
    if not user:
      raise HTTPException(status_code=HTTP_404_NOT_FOUND, detail="Invalid Credentials")
```

but not when used as dependency:

```python
@app.get("/posts", response_model=List[schemas.Post], tags=["posts"])
def list_posts(user=Depends(auth_manager), db: Session = Depends(get_db), skip: int = 0, limit: int = 100) -> Any:
  posts = actions.post.get_all(db=db, skip=skip, limit=limit)
  return posts
```

there error:

```
File "./backend/actions.py", line 78, in get_by_email
    return db.query(self.model).filter(self.model.email == email).first()
AttributeError: 'generator' object has no attribute 'query'
```

looks like the session is a generator: doesn't return a DB, the issue is not with your package, I've been thinking to replace sqlalchemy with TortoiseORM or another async SQLA package.

**Comment by MushroomMaula** [comment]
Have a look at these issues in the FastAPI repo [#1693](https://github.com/tiangolo/fastapi/issues/1693) and [#631](https://github.com/tiangolo/fastapi/issues/631) they might have a solution for your problem, it seems like using a generator inside a dependency doesn't work

**Comment by sid3r** [comment]
@MushroomMaula ok I get it now, can't use Depends() if the function using is not encapsulated in another Depends(), the issue is clear now, the function is never resolved. I'll try the context then and see.

**Comment by sid3r** [comment]
@MushroomMaula moved to TortoiseORM, it's working fine. Thankfully I'm just setting up the project base but it may be a problem for devs adding the package to an existing project and already using sqlachemy.orm.session. You should maybe add that information to the readme.md. thanks for the help.

**Comment by MushroomMaula** [comment]
Nice to hear that it's working now. I will update the docs and include a working example until passing more arguments to the`user_loader` is supported.

**Comment by buckettt** [comment]
Came across this same  issue.
A solution that I think works inspired by https://github.com/tiangolo/fastapi/issues/1693

This is only a simple test case so may break for something more complicated. 

Using a context manager mentioned here: https://fastapi.tiangolo.com/tutorial/dependencies/dependencies-with-yield/#using-context-managers-in-dependencies-with-yield

Gives: 
```python
class MySuperContextManager:
    def __init__(self):
        self.db = SessionLocal()

    def __enter__(self):
        return self.db

    def __exit__(self, exc_type, exc_value, traceback):
        self.db.close()

async def get_db():
    with MySuperContextManager() as db:
        yield db

```

...

```python



@app.post('/auth/token')
def login(data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db), ):
    print(data)
    email = data.username
    password = data.password

    user = load_user(email, db)
***  ....CREDENTIALS CHECK ETC.... ***

@manager.user_loader
def load_user(email: str, db: Session = None):  # could also be an asynchronous function
    if not db:
        with MySuperContextManager() as db:
            result = db.query(User).filter(User.email == email).one()
            return result
    try:
        result = db.query(User).filter(User.email == email).one()
    except:
        return None
    return result

@app.get('/protected')
def protected(username=Depends(manager)):
    return { 'name': username }

```

**Comment by sid3r** [comment]
@buckettt Hey, thank you, I've already tested the context manager but I've finally opted for another SQLA ORM, hope your response help others who face the same, your solution looks great.

**Comment by MushroomMaula** [comment]
I just added support for passing extra argument to the callback, aslong as they are known beforehand, in version 1.7.0
