### ISSUE TITLE
error checking inheritance of fastapi.params.Depends object

### ISSUE THREAD

**Issue by Alex-CodeLab** [MushroomMaula/fastapi_login#3]
I keep getting this error when trying the example for the `/protected` endpoint

>  File "pydantic/validators.py", line 569, in find_validators
> RuntimeError: error checking inheritance of <fastapi.params.Depends object at 0x7f6e17ddb940> (type: Depends)

**Comment by MushroomMaula** [comment]
Thanks for pointing this out thats actually a typo in the readme it should be 
```py
def protected_route(user=Depends(manager))
# typo here             ^
```
