### ISSUE TITLE
Redirect back to previous page

### ISSUE THREAD

**Issue by jccolazo** [MushroomMaula/fastapi_login#31]
Hello I wanted to know if there is any way to redirect back from the page the user was before login.
Situation:

user tries to enter an endpoint: localhost/example , but is protected by fastapi login, so it is redirected to localhost/login.

My question: is there anyway to go back to  localhost/example automatically once user is logged in in localhost/login ?
 Thanks.

**Comment by MushroomMaula** [comment]
This is not directly possible using the standard `Request`/`Response` object provided by `starlette`, however if you are using the exception handeling way from the examples, you can send the url you get redirected from as a query parameter to the login route.

```python
def exc_handler(request, exc):
    """
    Redirect user to login page
    """
    # get the relative url and its query parameters
    # so we can pass it on to the login route
    # not sure if this covers all edge cases, there might be better ways to build the url
    redirect_from = f"{request.url.path}?{request.url.query}"
    redirect_to = f"/login?original={redirect_from}"
    return RedirectResponse(url=redirect_to)

@app.get("/login")
def login(original: typing.Optional[str] = None):
    # ... normal login stuff
    # check if original set if not redirect to homepage or whatever
    if original is None:
        original = "/"
    response = RedirectResponse(original)
    # its a good idea to set the access token as a cookie on the response
    # so we dont get redirected back here
    # please note that `use_cookie` has to be set to True for this to work
    manager.set_cookie(response, access_token)
    # redirect back to original route
    return response
```

**Comment by jccolazo** [comment]
@MushroomMaula  Thanks ! That really helped!
