### ISSUE TITLE
OAuth Scopes?

### ISSUE THREAD

**Issue by lowercase00** [MushroomMaula/fastapi_login#43]
Hey there, thanks a lot for the package, been trying it out an app right now, and it seems to work great.

I could understand how should I use it, implement it with OAuth Scopes, couldn’t find anything in the docs.

Reading FastAPI docs, I’m guessing it shouldn’t be that much complex, but not really sure tbh. Totally willing to contribute as well, but I think I would need some
guidance on how to implement this feature.

Anyways, thanks a lot!

**Comment by MushroomMaula** [comment]
I have actually been thinking about adding OAuth scopes for a while and just haven't been sure, what would be the best way to implement the interface. It will probably lead to a new class, if you have any ideas please let me know.
The actual implementation doesn't seem to hard, if I have some time this week I will it add to the package.

**Comment by MushroomMaula** [comment]
I have just released version 1.6.2 which should now support OAuth2 scopes.
If you encounter any problems please let me know.
