### ISSUE TITLE
[Suggestion] custom exception

### ISSUE THREAD

**Issue by kigawas** [MushroomMaula/fastapi_login#55]
Now the exception is always `InvalidCredentialsException`:

```python
def __init__(self, ...):
    ...
    self._not_authenticated_exception = InvalidCredentialsException
```

`not_authenticated_exception` has a setter, but `auto_error` is set `False` at the same time.

```python
    @not_authenticated_exception.setter
    def not_authenticated_exception(self, value: Exception):
        """
        Setter for the Exception which raises when the user is not authenticated.
        Sets `self.auto_error` to False in order to raise the correct exception.

        Args:
            value (Exception): The Exception you want to raise
        """
        assert issubclass(value, Exception)  # noqa
        self._not_authenticated_exception = value
        # change auto error setting on OAuth2PasswordBearer
        self.auto_error = False
```

Sometimes users may want to inject a custom exception to be raised and handled by FastAPI exception handlers, so what about add an argument like `custom_exception: Exception = None` and remove `not_authenticated_exception.setter` as well as `auto_error` stuff?

**Comment by MushroomMaula** [comment]
Sounds good.
`auto_error` however is internally used by its super class `OAuth2PasswordBearer` as one can see [here](https://github.com/tiangolo/fastapi/blob/1760da0efa55585c19835d81afa8ca386036c325/fastapi/security/oauth2.py#L163) so it will still be needed to set it to false.

**Comment by MushroomMaula** [comment]
Done in version 1.7.0
