### ISSUE TITLE
OpenAPI Support

### ISSUE THREAD

**Issue by athul** [MushroomMaula/fastapi_login#6]
Hey, Thanks for building this. Is OpenAPI supported? I can't see an Autheticate button for the same. I'm a noob in this stuffs. Correct me if I'm wrong too

**Comment by MushroomMaula** [comment]
That's correct the authentication button is missing, however I plan to add this feature in a future update

**Comment by MushroomMaula** [comment]
OpenAPI support, as the default OAuth2SupportBearer from FastAPI provides, should be working with the newest update. Please reach out to me if you encounter any problems.
