### ISSUE TITLE
Error on 1.7.2 for fastapi_login import LoginManager

### ISSUE THREAD

**Issue by muke888** [MushroomMaula/fastapi_login#61]
Hey there, 

I am getting an error on 1.7.2 when importing `from fastapi_login import LoginManager`,
the result I get is: 

```
  File "/usr/local/lib/python3.7/dist-packages/fastapi_login/utils.py", line 11
    def __call__(self, /, *args, **keywords):
                       ^
SyntaxError: invalid syntax
```

Not sure if the ` /,` is just a placeholder and has not been updated?

Also, how do I pass on args for the user_loader? In the docs it says:
```
>>> @manager.user_loader(...)  # Arguments and keyword arguments declared here are passed on
>>> def get_user(user_identifier, ...):
...     # get user logic here
```
Can you give an example? I am not sure if the below would be correct?
```
@manager.user_loader(session: Session = Depends(get_session))
def get_user_by_email(email: str, db: session):
    user = db.query(Hero).filter(Hero.email == email).first()
    return user
```

Regards

**Comment by MushroomMaula** [comment]
I figured out why your code isn't working, as your error states you are calling `get_user_by_email` in `"/app/./app/web/auth/route_login.py"` on line 27, however if you changed your `get_user_by_email` to the following:
```py
@manager.user_loader(session_provider = get_session)
def get_user_by_email(email: str, session_provider ):
    db = session_provider()
    user = db.query(Hero).filter(Hero.email == email).first()
    return user
```
you are missing the `session_provider` argument in your call.
You either have to pass `get_session` or reimplement your old code, which kind of defeats the purpose of adding the extra argument.

This is how you could change it, I however would just pass `get_session` to the function.
```py
@manager.user_loader(session_provider=get_session)
def get_user_by_email(email: str, session_provider=None) -> Optional[Hero]:
  """
  Can be used like this:
  get_user_by_email(email) or get_user_by_email(email, session_provider=...)
  """ 
  if  session_provider is None:
    with Session(engine) as db:
      return db.query(Hero).filter(Hero.email == email).first()
  else:
    db = session_provider()
    return db.query(Hero).filter(Hero.email == email).first()
```
