### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'set_cookie'

### ISSUE THREAD

**Issue by jabhishek87** [MushroomMaula/fastapi_login#66]
`@app.post('/login')
def login(data: UserCreate, response: Response, db=Depends(get_db)):
    email = data.email
    password = data.password

    user = get_user(email)  # we are using the same function to retrieve the user
    if user is None:
        raise InvalidCredentialsException  # you can also use your own HTTPException
    elif not verify_password(password, user.password):
        raise InvalidCredentialsException

    access_token = manager.create_access_token(
        data=dict(sub=user.email)
    )
    response = {
        'access_token': access_token,
        'user': UserResponse(**user.__dict__),
        'token_type': 'Bearer'
    }
    manager.set_cookie(response, access_token)
    return response`

**Comment by MushroomMaula** [comment]
This error occurs because you named your the dictionary response, `manager.set_cookie` expects an actual response object, like the one defined in your arguments of the function.

**Comment by jabhishek87** [comment]
Thanks

**Comment by jabhishek87** [comment]
better example https://github.com/MushroomMaula/fastapi_login/issues/62
