### ISSUE TITLE
Generator as the `user_loader` argument

### ISSUE THREAD

**Issue by sz3lbi** [MushroomMaula/fastapi_login#67]
Hello,

I have the generator as below which gives me the database session:
```python
def get_db() -> Generator:
    db = None
    try:
        db = SessionLocal(future=True)
        yield db
    finally:
        if db is not None:
            db.close()
```

I have declared the `user_loader` the way shown (tried the no-bracket version of providing callable).
```python
@manager.user_loader(db_session=get_db())
def query_user(email: EmailStr, db_session: Session):
    user = db_session.execute(select(User).where(User.email == email)).scalars().first()
    return user
```

The reason I want the `get_db` to be `user_loader` parameter is that my FastAPI routers depend on the `get_db` and the `fastapi-login` `manager` at the same time and inside, I just call the method:
```python
existing_user = query_user(user_in.email, db)
```
Example route:
```python
@router.get("/users", response_model=List[UserSchema])
def get_users(
    response: Response,
    db: Session = Depends(get_db),
    skip: int = 0,
    limit: int = 100,
    user: User = Depends(manager),
) -> Any:

    if user is None:
        logger.info("Unauthorized user tried to get users list.")
        raise HTTPException(401)
    elif not user.is_superuser:
        logger.info(f"Not-superuser {user} tried to get users list.")
        raise HTTPException(401)

    total = db.scalar(select(func.count(User.id)))
    users = db.execute(select(User).offset(skip).limit(limit)).scalars().all()
    response.headers["Access-Control-Expose-Headers"] = "Content-Range"
    response.headers["Content-Range"] = f"{skip}-{skip + len(users)}/{total}"

    logger.info(f"{user} getting all users with status code {response.status_code}")
    return users
```

The problem is that when trying to call route depending on the `manager`, I get the exception:
 `AttributeError: 'generator' object has no attribute 'execute'`

What should I do to get it working? Thanks in advance.

**Comment by MushroomMaula** [comment]
Hey, 
This is a known limitation of the current implementation, as FastAPI calls `next` on the returned Generator when used with `Depends`, which `fastapi-login`, does not. So what is happening is that `db_session=get_db()` sets `db_session` to the returned generator, but as next is never called on it, it never resolves to the actual database session.
What you can do is either set `db_session` to `next(get_db())`, which kind of defeats the purpose of the session, as this is only evaluated once and not on every request, or have a look at [issue 29](https://github.com/MushroomMaula/fastapi_login/issues/29), where others already discussed various solutions and ideas.

**Comment by sz3lbi** [comment]
It works like a charm now, thanks!
The other thing is I had user ID as the primary key and the email as the `user_loader` parameter which cased some unexpected problems :D I created the other function for querying for a user with an email and changed the `user_loader` one to the ID-dependent.
