### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by agent666** [MushroomMaula/fastapi_login#68]
Hi I'm planning to use fastapi_login in a project.
I have found the:

```
    user = request.state.user
    if user is None:
        raise HTTPException(401)
    # assuming our user object has a is_admin property
    elif not user.is_admin:
        raise HTTPException(401)
    else:
        return user
```

But i don't understand how `is_admin` changed/set?

**Comment by MushroomMaula** [comment]
`user` in this case is the object returned by the function decorated with `user_loader()`. In the example above it is assumed that  the object returned by that function has the `is_admin` property. 
How you change/set `ìs_admin` is completely up to you, as you decide what object `user` is.

**Comment by MushroomMaula** [comment]
Let's say you have the following user object and `user_loader` set up:

```py
class User(pydantic.BaseModel):
    name: str
    is_admin: bool = false


@manager.user_loader()
def get_user(name: str) -> User:
     return db_sess.extecute(select(UserTable).where(UserTable.name == name).first()
```
Then you can change `is_admin` as you would with any other `pydantic.BaseModel` class.

**Comment by agent666** [comment]
> Let's say you have the following user object and `user_loader` set up:
> 
> ```python
> class User(pydantic.BaseModel):
>     name: str
>     is_admin: bool = false
> 
> 
> @manager.user_loader()
> def get_user(name: str) -> User:
>      return db_sess.extecute(select(UserTable).where(UserTable.name == name).first()
> ```
> 
> Then you can change `is_admin` as you would with any other `pydantic.BaseModel` class.
