### ISSUE TITLE
Encoding & Decoding Tokens with RS256 (RSA)

### ISSUE THREAD

**Issue by filwaline** [MushroomMaula/fastapi_login#70]
LoginManager only accept single `secret` parameter in str type, how can it use private key to sign and public key to verify?

It seems only possible solution is using two different instances?
```
sign_manager = LoginManager(secret=private_key, ...)
verify_manager = LoginManager(secret=public_key, ...)

token = sign_manager.create_access_token(...)
payload = verify_manager._get_payload(token)
```

Or i am misunderstanding?

**Comment by MushroomMaula** [comment]
Right now that is correct I didn't consider using RSA for signing the keys.
I will have to look how to implement this use case without making the process to different from using a single secret.

**Comment by filwaline** [comment]
> Right now that is correct I didn't consider using RSA for signing the keys.
> I will have to look how to implement this use case without making the process to different from using a single secret.

One of possible solutions:
Input private key as secret, then derive it's public key for verify.
 https://stackoverflow.com/questions/696472/given-a-private-key-is-it-possible-to-derive-its-public-key

**Comment by MushroomMaula** [comment]
Just publised the new version.
