### ISSUE TITLE
Cookie for request.state.user

### ISSUE THREAD

**Issue by LovelessCodes** [MushroomMaula/fastapi_login#71]
When you create an access token and set it as a cookie - can you somehow call the user like how it is in the documentation?
```py
    user = request.state.user
    if user is None:
        raise HTTPException(401)
```
or is that simply not possible when utilizing cookies?

**Comment by Matthieu-LAURENT39** [comment]
sorry for resurrecting a dead issue, but i'm having the exact same issue, trying to use `request.state.user` with cookie authentification.
Did you manage to figure out how to do it?
