### ISSUE TITLE
Enforcing authorization

### ISSUE THREAD

**Issue by mattduffield** [MushroomMaula/fastapi_login#80]
Hello, how would I go about enforcing authorization? For example specific roles and permissions. I currently do this by not showing menus but that still leaves the endpoints open if the user knows the URL to enter to access a given page. I would like to enforce this when the request is be sent just like Authentication but this time for specific Authorization. I am not sure where is the best to handle this? I was thinking in the user_loader function and raise an exception if the user is not authorized even though authenticated for a given route/request.

Thanks in advanced!

**Comment by MushroomMaula** [comment]
What exactly do you mean by enforce authorization?
If you want to raise an error, when a user tries to access a protected route and is not authenticated/has no permission, you can simply use the login manager as a dependency as shown in the [documentation](https://fastapi-login.readthedocs.io/usage/#usage-as-a-dependency).
If you need more fine grained permissions than just authenticated or not, [OAuth2 scopes](https://fastapi-login.readthedocs.io/advanced_usage/#oauth2-scopes) might help.

**Comment by mattduffield** [comment]
Pretty much the same thing that happens when you are not authenticated. An exception is thrown and you are directed to the Login or a custom page. What I am trying to establish is that you can be authenticated yet still not have access to a given route or resource. I am currently doing this at every route but I was hoping for a more centralized manner.

**Comment by MushroomMaula** [comment]
It's possible to use [APIRouter](https://fastapi.tiangolo.com/tutorial/bigger-applications/#another-module-with-apirouter) and add the dependency directly, such that all routes belonging to the router will automatically enforce it.
This way you could create a router for e.g. your admin dashboard and add a dependency which requires the admin scope.

**Comment by mattduffield** [comment]
That sounds like what I would like to accomplish. Is there any example how this works with your library or is this completely separate? Thanks for your help so far...

**Comment by MushroomMaula** [comment]
It would look roughly like the following. Please not that you then also have to add the scopes when creating the access token for the desired user.

```py
from fastapi import APIRouter, Security

manager = LoginManager(..., scopes={"admin": "Access admin panel"})
router = APIRouter(
    prefix="/admin", 
    dependencies=[Security(manager, scopes=["admin"]]
)

@router.get('/protected')  # This will end up at '/admin/protected'
def protected_route()  # Should only be accessible when the user has the 'admin' scope
    ...

# Include the router in your app
app = FastAPI()
app.include_router(router)


# Now in your login route you need to also add the scope to your desired user
@app.post('/login')
def login(...):
    ...
    if db_user.is_admin():
        scopes = ['admin']
    else:
        scopes = []
    return manager.create_access_token(..., scopes=scopes)
```

**Comment by mattduffield** [comment]
Thanks for the example. All of my permissions (scopes) are dynamic and can change if the client wishes to create new permissions or remove an existing one. How would this work with the LoginManager needing it in the constructor? Also, are you able to control where the user is directed if they don't have a given permission (scope)? e.g. Not Authorized page, etc.

**Comment by mattduffield** [comment]
Given that my routes are completely dynamic as well as admins can adjust permissions whenever needed, I had to roll out my own implementation. This is an excellent example for those that have static known routes.
