### ISSUE TITLE
How can I invalidate the Token?

### ISSUE THREAD

**Issue by mayank091193** [MushroomMaula/fastapi_login#82]

**Comment by stv8** [comment]
I don't think it's possible to invalidate JWTs. You would have to use server-side session management to be able to do that.

**Comment by MushroomMaula** [comment]
Yes thats correct, JWT's are meant to work without having to store the information about the session on the server, but that also means that it is not trivial to invalidate the tokens.
I suggest you set a short expiry time and remove the token on the client side when the user wants to log out.
