### ISSUE TITLE
Logout route

### ISSUE THREAD

**Issue by gurbaaz27** [MushroomMaula/fastapi_login#87]
Hi! I am new to fastapi and came across this useful library, which now I am using to implement user login and authentication.
I also want to create a route for user logout, and wanted to know how to do that? Would that require doing something with LoginManager, as it is responsible for generating access_token?

**Comment by MushroomMaula** [comment]
This is not directly supported using JSON web tokens. Have a look [here](https://github.com/MushroomMaula/fastapi_login/issues/82)
