### ISSUE TITLE
Howto get FASTAPI to use token in requests?

### ISSUE THREAD

**Issue by sderuiter** [MushroomMaula/fastapi_login#88]
I'm sure the answer is incredibly simple, but I've searched for a week now, and just can't figure this out...

I've followed the guide on using fastapi-login with the standard example:

```
app = FastAPI()
manager = LoginManager(FASTAPI_LOGIN_SECRET, '/auth/login')
```
```
DB = {
    'users': {
        'sander': {
            'name': 'sander',
            'password': 'hello'
        }
    }
}
```
```
@manager.user_loader()
def query_user(user_id: str):
    """
    Get a user from the db
    :param user_id: E-Mail of the user
    :return: None or the user object
    """
    return DB['users'].get(user_id)
```
```
@app.post('/auth/login')
def login(data: OAuth2PasswordRequestForm = Depends()):
    email = data.username
    password = data.password

    user = query_user(email)
    if not user:
        # you can return any response or error of your choice
        raise InvalidCredentialsException
    elif password != user['password']:
        raise InvalidCredentialsException

    access_token = manager.create_access_token(
        data={'sub': email}
    )
    return {'access_token': access_token}
```
```
@app.get('/protected')
def protected_route(user=Depends(manager)):
    return {'user': user}
```
```
@app.get("/user/register", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("user/register.html", {"env": env, "request": request})

```

My form has:
```
<form action="/auth/login" method="POST">
```

Now, visiting `/user/register` and submitting the form gives me the `access_token`.

**My expectation:** If I now visit `/protected` I should should see the logged in user. 
**Reality:** I get a `Not authenticated` error. 

Now, when I visit the `/docs` route and try authorization in Swagger, it does work.

I've identified the issue as my browser not sending the Authorization header with the received token. 
As there's no example of a frontend for this, I just don't know what to do with the token to make the browser use it on subsequent requests?

**Comment by MushroomMaula** [comment]
When you make new requests to the backend you have to include the access token in either the [header](https://stackoverflow.com/questions/41471563/how-to-add-jwt-to-authorization-header) or use [cookies](https://fastapi-login.readthedocs.io/advanced_usage/#cookies) which handels this automatically.
