### ISSUE TITLE
How to do partial access ? 

### ISSUE THREAD

**Issue by AyushSehrawat** [MushroomMaula/fastapi_login#89]
How can you do something like this - 
User can access the endpoint but depending on whether he is logged in or not, the responses will be different?

**Comment by MushroomMaula** [comment]
This should be possible to do with either [custom exception handeling](https://fastapi-login.readthedocs.io/advanced_usage/#exception-handling) or using the manager as a [middleware](https://fastapi-login.readthedocs.io/advanced_usage/#middleware). 
However I have to admit that both of those options seem rather overkill if this is needed for a single endpoint.

**Comment by AyushSehrawat** [comment]
Yeah, i mean same. Also if i implement it in the `custom exception handeling` it may ruin your work if you only intend to do it for some endpoints. Also i did consider middleware but thought that i would have to change whole of code. The stuff i did was ( in the next comment )

**Comment by AyushSehrawat** [comment]
```py
@app.exception_handler(NotAuthenticatedException)
async def auth_exception_handler(request: Request, exc: NotAuthenticatedException):
    #return RedirectResponse(url='/login')
    return JSONResponse({"error": "Not authenticated"}, status_code=401)

@app.get("/")
async def index(request: Request):
    access_token = request.cookies.get("access-token")
    if access_token:
        dat = await manager.get_current_user(access_token)
        if dat:
            return {"user": dat["username"]}
        else:
            return {"user": "anonymous"}
    #return cur.TemplateResponse("index.html", {"request": request})
```
It's still in beta cus dat also gives the user or null, so gotta add another check there. But for now this method worked... I get the access_token via request ( for some reasons that fastapi `access_token : Optional[str] = Cookie(None)` akways gave None) and then using the `get_current_user(access_token)` i validate it ( had to read all your reference and repo files ;-; ).

In short, this works :)

**Comment by MushroomMaula** [comment]
What exactly do you want to return if the user is not authenticated?
In case you want to return `JSONResponse({"error": "Not authenticated"}, status_code=401)` everytime a user tries to access a protected route, the custom exception way should be sufficient.

**Comment by AyushSehrawat** [comment]
> What exactly do you want to return if the user is not authenticated? In case you want to return `JSONResponse({"error": "Not authenticated"}, status_code=401)` everytime a user tries to access a protected route, the custom exception way should be sufficient.

As i said its in testing stage... What i really want is - If user is logged in show different content in html and if user is a guest show different stuff ( for same html file ) . Checks will be made depending on it, and depending on that i will edit the html

**Comment by AyushSehrawat** [comment]
It's just like how github shows two different templates on guest and logged in ( though in my case same file edited )

**Comment by MushroomMaula** [comment]
I see.
In that case I would suggest using the middleware approach. 
Instead of using `Depends(manager)` you could then write your own dependency that will be able to return your user object if the user is not authenticated, that should not be too much to refactor.
If that is too much to change, I think it should be possible to subclass the `LoginManager` class and overwrite the `__call__` method to catch any errors that would be raised  and then return your user object.

**Comment by MushroomMaula** [comment]
```
CustomLoginManager(LoginManager):

def __call__(self, request, security_scopes=None):
    try:
        return super().__call__(request, security_scopes)
    except:
        return {"user": "anonymous"} 
```
Something like this.

**Comment by AyushSehrawat** [comment]
Oh kk....Will see the middleware approach and the customloginmanager way, if any one of it seems easier to me i will implement that only. Though what are your views on the method i used? ?

**Comment by AyushSehrawat** [comment]
I intend to use this only on one endpoint

**Comment by MushroomMaula** [comment]
To be honest if you only need this for one endpoint I would still use one of my suggested methods, rather the middleware approach, and use the normal dependency if you need the endpoint to be protected.
I think your way looks good as well, but you should add some exception handling around `manager.get_current_user` because this raises an exception if no user is found matching the token.

If I have enough time in the next few weeks I will maybe restructure some of the code and make it easier to adapt to this use case.

**Comment by AyushSehrawat** [comment]
Yeah, middleware seems better and easier to me. Will try to implement that only.
> If I have enough time in the next few weeks I will maybe restructure some of the code and make it easier to adapt to this use case.
Would be nice.

Also add some functionality for bigger fastapi applications, currently i have separated the manager in another file and import it when using anywhere  like `from ..multiuse.manager import manager` and then

**Comment by AyushSehrawat** [comment]
Thank for your help and fast response. Cya! 🚀
