### ISSUE TITLE
No version given for pyjwt dependency

### ISSUE THREAD

**Issue by HealYouDown** [MushroomMaula/fastapi_login#94]
fastapi-login does not have a version dependency for `pyjwt`. The change in f31b6718b8b8e23adda33de9cf18972b4d129830 however expects you to have version >= 2.0, as before, `jwt.encode` returned the token as `bytes`, not as `str`.

Propsed fix would be to set the version to `^2.0` instead of `*`.
Alternatively, if support for all version is still wanted, you could also check the return type of `jwt.encode` and cast it to `str`.

**Comment by zandb2009** [comment]
Yes, I found the same problem.
